config/routes.rb
Rails.application.routes.draw do
   scope "(:locale)", locale: /en|zh/ do
     resources :bookings
     resources :bookings do
       resources :charges 
       member do
         put :cancel    #-> domain.com/bookings/:id/cancel
         put :engage    #-> domain.com/bookings/:id/engage       
         put :disengage #-> domain.com/bookings/:id/disengage  
         put :confirm   #-> domain.com/bookings/:id/confirm 
         put :complete  #-> domain.com/bookings/:id/complete
         put :reject    #-> domain.com/bookings/:id/reject
         put :expire    #-> domain.com/bookings/:id/reject
       end
     end
    # mount Upmin::Engine => '/admin'
	#  root to: 'visitors#index'
     root to: 'visitors#LetsNurse'
     get "customer_faq" => "visitors#faq"
     get "partner_faq"  => "visitors#faq2"
     get "legal" => "visitors#legal"
     devise_for :users
     resources :users
     resources :orders
     resources :orders do 
       collection do 
        get :open
      end
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  include AASM
  
  #before_save :calculate_refund
  
  belongs_to :user
  belongs_to :nurse, :class_name => 'User', :foreign_key => 'nurse_id'
  has_many :charges, :dependent => :destroy
  accepts_nested_attributes_for :charges, :allow_destroy => :true
  
  enum hospital: { 嘉諾撒醫院: 1, 播道醫院: 2, 香港港安醫院: 3, 浸信會醫院: 4, 養和醫院: 5, 明德國際醫院: 6, 
    寶血醫院: 7, 聖保祿醫院: 8, 聖德肋撒醫院: 9, 荃灣港安醫院: 10, 仁安醫院: 11 }
  enum status: [:Open, :Matched, :Completed, :Cancelled, :Rejected, :Pending, :Expired, :Confirmed]
  enum payment: [:Paid, :Refunded, :NotPaid, :PaidOut]
  enum preferred_language: [:English, :中文, :Either]
  
  validates_presence_of :user_id, :order_datetime, :hours
#  validates :order_datetime, in_future: true 
  validate :future_order
  validates_numericality_of :hours, integer_only: true, gt: 0
  validates_numericality_of :fee, integer_only: true, within: 500..5000
  validates_numericality_of :cost, integer_only: true, within: 500..5000 
  validates :contact_phone_no,  :presence => true, 
                        :numericality => true,
                        :length => { :minimum => 8, :maximum => 8 }
  
  before_update :calculate_fee
  
  aasm(:status) do
    state :Open, :initial => true
    state :Rejected, :Cancelled, :Matched, :Completed, :Expired, :Confirmed

    event :engage do
      transitions :from => :Open, :to => :Matched
    end
    event :reject do
      transitions :from => [:Open, :Matched], :to => :Rejected
    end
    event :cancel do
      transitions :from => [:Open, :Matched, :Confirmed], :to => :Cancelled
    end
    event :confirm do
      transitions :from => :Matched, :to => :Confirmed
    end
    event :disengage do
      transitions :from => :Matched, :to => :Open
    end
    event :expire do
      transitions :from => [:Open, :Matched], :to => :Expired
    end
    event :complete do
      transitions :from => :Confirmed, :to => :Completed
    end
  end
  
  aasm(:payment) do
    state :NotPaid, :initial => true
    state :Refunded, :NotPaid, :Paid

    event :refund do
      transitions :from => :Paid, :to => :Refunded
    end
    event :pay do
      transitions :from => :NotPaid, :to => :Paid
    end
  end

  
  public
  
  def calculate_fee
    if self.hours == 4
      self.fee  = 999
      self.cost = 800
    elsif self.hours == 8
      self.fee  = 1899
      self.cost = 1500
    else
      self.fee  = 2799
      self.cost = 2200
    end
  end
  
    
  private
  
  def calculate_refund
    self.cancellation_datetime = Time.now
    if self.cancellation_datetime + 24.hours < self.order_datetime
      self.refund_amount = self.fee
    elsif self.cancellation_datetime + 4.hours < self.order_datetime
      self.refund_amount = 300
    else
      self.refund_amount = 500
    end
  end
  
  def self.i18n_hospitals(hash = {})
    hospitals.keys.each { |key| hash[I18n.t("hospitals.#{key}")] = key }
    hash
  end
  
  def future_order
    if order_datetime < Time.now
      errors.add(:order_datetime, "Only future date is allowed")
    end
  end 
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, 
    :cancel, :engage, :disengage, :complete, :expire, :reject]

  def cancel
    @booking.cancellation_datetime = Time.now
    if @booking.cancellation_datetime + 1.days < @booking.order_datetime
      @booking.refund_amount = @booking.fee
    elsif @booking.cancellation_datetime + (4/24.0) < @booking.order_datetime
      @booking.refund_amount = @booking.fee - 300
    else
      @booking.refund_amount = @booking.fee - 500
    end
    @booking.cancel!
    BookingMailer.delay.cancel_booking_to_user(@booking)
    BookingMailer.delay.cancel_booking_to_nurse(@booking)
    redirect_to bookings_path  
  end
  
  def engage
    @booking.nurse = current_user
    @booking.engage!
    BookingMailer.delay.engage_booking_to_user(@booking)
    BookingMailer.delay.engage_booking_to_nurse(@booking)
    redirect_to bookings_path 
  end
  
  def disengage
    BookingMailer.delay.disengage_booking_to_nurse(@booking)
    @booking.nurse = nil 
    @booking.disengage!
    BookingMailer.delay.disengage_booking_to_user(@booking)
    redirect_to bookings_path 
  end
  
  def expire
    redirect_to bookings_path  if @booking.expire!
  end
  
  def complete
    redirect_to bookings_path  if @booking.complete!
  end
  
  def reject
    BookingMailer.delay.reject_booking_to_user(@booking)
    if @booking.Matched?
      BookingMailer.delay.reject_booking_to_nurse(@booking)
    end 
    redirect_to bookings_path  if @booking.reject!
  end
  
  # GET /bookings
  # GET /bookings.json
  def index
    if current_user.customer? 
      @bookings = Booking.where(" user_id = ?", current_user.id).order('order_datetime desc')
    elsif current_user.admin?
      @bookings = Booking.all.order(order_datetime: :desc)
    else
      @bookings = Booking.where("nurse_id = ? or status = ? ",  current_user.id, Booking.statuses[:Open]).order(order_datetime: :desc)
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
#    @booking.payment_token = params[:stripeToken]
    @booking.calculate_fee
    @booking.status = :Open
    @booking.payment = :NotPaid
#    if @booking.valid?
#        customer = Stripe::Customer.create(
#          :email => params[:stripeEmail],
#          :source  => params[:stripeToken]
#        )
#
#        charge = Stripe::Charge.create(
#          :customer    => customer.id,
#          :amount      => @booking.fee * 100,
#          :description => 'client: '+@booking.user.name,
#          :currency    => 'hkd'
#        )
#    end
    respond_to do |format|
      if @booking.save 
        BookingMailer.delay.new_booking_to_user(@booking)
        if @booking.Open?
          BookingMailer.delay.new_booking_to_nurses(@booking)
        end
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { redirect_to new_booking_path, notice: 'We do not take back-dated order.' }
       # format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
#  rescue Stripe::CardError => e
#    flash[:error] = e.message
#    redirect_to new_booking_path
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :order_datetime, :hours, :hospital, :status, :location, :fee, :cost, :contact_person, :contact_phone_no, :payment_token, :nurse_id, :preferred_language, 
        :notes)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_content.html.erb
<div class="authform">

<!--Booking Record Info-->

    <p><strong><%= t('customer') %>: </strong><%= @booking.user.name %></p>
    <% if !current_user.customer?  %>
      <p><strong><%= t('customer_rating') %>: </strong><%= @booking.user.rating %></p>
    <% end %>
  
    <p><strong><%= t('order_time') %>: </strong><%= @booking.order_datetime.strftime("%d/%m/%Y - %l:00 %p") %></p>
    <p><strong><%= t('duration') %>: </strong><%= @booking.hours %> <%= t('hours') %></p>

    <p><strong><%= t('location') %>: </strong>
    <% if @booking.hospital %>
      <%= I18n.t :"hospitals.#{@booking.hospital}" %>
    <% end %>
    <%= @booking.location %></p>

    <% if current_user.admin? or current_user.customer? %>
      <p><strong><%= t('fee') %>: </strong><%= number_to_currency(@booking.fee, precision: 0) %> (<%= t_enum(@booking, :payment) %>) </p>
    <% end %>
    <% if current_user.admin? or current_user.partner? %>
      <p><strong><%= t('cost') %>: </strong><%= number_to_currency(@booking.cost, precision: 0) %></p>
    <% end %>
  
    <% if !current_user.partner? or !@booking.NotPaid? %>
      <p><strong><%= t('contact') %>: </strong><%= @booking.contact_person %></p>
      <p><strong><%= t('phone_no') %>: </strong><%= @booking.contact_phone_no %></p>
    <% end %>
  
    <p><strong><%= t('preferred_language') %>: </strong><%= @booking.preferred_language %></p>

    <% if @booking.nurse %>
      <p> <strong><%= t('nurse') %>: </strong><%= @booking.nurse.name %> (<%= t('nurse_rating') %>: <%= @booking.nurse.rating %>) </p>
      <div><%= image_tag @booking.nurse.image.url(:thumb), class: "img-responsive img-thumbnail img-circle" %></div>
    <% end %>
  
    <% if !current_user.customer? or !@booking.NotPaid? %>
      <% if @booking.nurse %>
      <p><strong><%= t('nurse_phone_no') %>: </strong><%= @booking.nurse.phone_no %></p>
      <% end %>  
    <% end %>
  
    <p><strong><%= t('status') %>: </strong><%= t_enum(@booking, :status) %> </p>
  
    <% if current_user.admin? %>
      <p> <strong>Stripe Token: </strong><%= @booking.payment_token %> </p>
    <% end %>

    <% if @booking.Cancelled? and @booking.cancellation_datetime%>
      <p> <strong><%= t('cancel_time') %>: </strong><%= @booking.cancellation_datetime.strftime("%d/%m/%Y - %l:%M %p") %> </p>
      <% if @booking.refunded? %>
        <p> <strong><%= t('refund_amount') %>:</strong> HK$ <%= @booking.refund_amount %> <%= t('was_refunded') %> </p>
      <%else %>
        <p> <strong><%= t('refund_amount') %>:</strong> HK$ <%= @booking.refund_amount %> <%= t('will_be_refunded') %> </p>
      <% end %>
    <% end %>
  
  <% if  current_user.customer? and @booking.Matched? %>
    <%= render @booking.charges %>
    <%= render 'charges/form' %>
  <% end %>
  
<!--Booking Record Info-->
  

  

app/views/bookings/_details.html.erb
  <p><strong>User: </strong><%= @booking.user.name %></p>
  <p>
    <strong>Time: </strong><%= @booking.order_datetime.strftime("%d/%m/%Y - %l:00 %p") %>
  </p>
  <p><strong>Hours: </strong><%= @booking.hours %> hours</p>
  <p><strong>Hospital: </strong><%= @booking.hospital %></p>
  <p><strong>Location: </strong><%= @booking.location %></p>
  <% if current_user.admin? or current_user.customer? %>
  <p><strong>Fee: </strong><%= number_to_currency(@booking.fee) %></p>
  <% end %>
  <% if current_user.admin? or current_user.partner? %>
    <p><strong>Cost: </strong><%= number_to_currency(@booking.cost) %></p>
  <% end %>
  <p><strong>Contact: </strong><%= @booking.contact_person %></p>
  <p><strong>Phone No: </strong><%= @booking.contact_phone_no %></p>

  <% if @booking.nurse %>
    <p> <strong>Nurse: </strong><%= @booking.nurse.name %></p>
  <% else %> 
    <p> <strong>Nurse: </strong></p>
  <% end %>
  
  <p><strong>Status: </strong><%= @booking.status %></p>
  
  <% if current_user.admin? %>
    <p> <strong>Stripe Token: </strong><%= @booking.payment_token %> </p>
  <% end %>
    
  <p> <strong>Payment: </strong><%= @booking.payment %> </p>

app/views/bookings/_form.html.erb
<div class="authform">
  
    <% if @booking.new_record? %>
    <% end %>
  
    <%= simple_form_for(@booking) do |f| %>

    <div class="form-inputs">

        <% if @booking.new_record? %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        <h3><%= t("New_Booking") %></h3> <br>
        <% else %>
          <h3><%= @booking.user.name %>'s <%= t("Booking") %></h3>
        <% end %>
      
        <%#= f.input :order_datetime, discard_minute: :true, minute_step: 60, ampm: true %>
      
      <% if @booking.new_record? or @booking.Open? %>
          <p><%= f.datetime_select :order_datetime, { discard_minute: true, minute_step: 60, ampm: true} %></p>
          <%= f.input :hours, label: t("hours"), collection: [[4, '4:  $999'], [8, ' 8:  $1,899'], [12, '12: $2,799'] ], as: :radio_buttons, label_method: :last, value_method: :first%>
        <% else %>
          <p><strong><%= t('order_time') %>: </strong><%= @booking.order_datetime.strftime("%d/%m/%Y - %l:00 %p") %></p>
          <Strong><%= t("duration") %>: <%= @booking.hours %> <%= t("hours") %></strong> <br><br>
        <% end %>
      
      <%= f.input :hospital, collection: Booking.i18n_hospitals %>
        <%= f.input :location %>

        <% if current_user.admin? %>
          <%= f.association :nurse, :as => :collection_select, collection: User.partner %>
        <% end %>

      <% if !@booking.contact_person %>
        <% @booking.contact_person = current_user.name %>
      <% end %>
      <% if !@booking.contact_phone_no %>
        <% @booking.contact_phone_no = current_user.phone_no %>
      <% end %>
        <%= f.input :contact_person %>
        <%= f.input :contact_phone_no %>
      
      <%= f.input :preferred_language, collection: Booking.preferred_languages.keys  %>
      
        <% if @booking.new_record? %>
      <%= f.hidden_field :status, value: :Open %>
        <% else %>
          <%#= f.input :status, collection: Booking.statuses.keys %>
          <strong><%= t("status") %>: <%= @booking.status %></strong>
        <% end %>  
    </div>  
  
  <% if @booking.Matched? or @booking.Open? or @booking.new_record? %>
      <br>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
  <% end %>
  
<% end %>

</div>

app/views/bookings/edit.html.erb
<!--<h1>Editing Booking</h1>-->

<%= render 'form' %>

<!--
<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>
-->

app/views/bookings/index.html.erb
<% if current_user.partner? %>
  <h3><%= t('booking') %>(<%= t('partner') %>)</h3>
<% elsif current_user.customer? %>
  <h3><%= t('booking') %>(<%= t('customer') %>)</h3>
<% elsif current_user.admin? %>
  <h3><%= t('booking') %>(<%= t('admin') %>)</h3>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <% if current_user.partner? %>
         <th><%= t('customer') %></th>
      <% end %>
      <th><%= t('order_time') %></th>
      <th><%= t('hours') %></th>
<!--      <th>Hospital</th>-->
      <th><%= t('location') %></th>
      
      <% if current_user.admin? %>
               <th><%= t('nurse') %></th>
      <% end %>


      <th><%= t('status') %></th>
      <% if current_user.admin? or current_user.customer? %>
        <th><%= t('fee') %></th>
        <th><%= t('payment') %></th>
      <% end %>
      <% if current_user.admin? or current_user.partner? %>
        <th><%= t('cost') %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <% if current_user.partner? %>
          <td><%= booking.user.name %></td>
        <% end %>
        <% if booking.order_datetime? %>
        <%#= booking.order_datetime.strftime("%Y/%m/%d %l %p") %>
        <td><%= booking.order_datetime.strftime("%m/%d %l%p") %> </td> 
        <% end %> 
        <td><%= booking.hours %></td>
<!--        <td><%= booking.hospital %> -->
        <td><%= t_enum(booking, :hospital) %>
            <%= booking.location %></td>

        <% if current_user.admin? %>
          <% if booking.nurse_id != nil  %>
            <td><%= booking.nurse.name %></td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
        
        <td><%= t_enum(booking, :status) %>
        
        <% if current_user.admin? or current_user.customer? %>
          <td><%= number_with_delimiter(booking.fee) %></td>
        <td><%= t_enum(booking, :payment) %></td>
        <% end %>
        <% if current_user.admin? or current_user.partner? %>
          <td><%= number_with_delimiter(booking.cost) %></td>
        <% end %>

<!--        Action Button -->
        
        <%= link_to booking do %>
          <td>
          <%= link_to booking  do %>
              <i class="glyphicon glyphicon-zoom-in"></i>
          <% end %>           
          </td>
        <% end %>
        
        <% if current_user.admin? %>
          <td>
          <%= link_to edit_booking_path(booking)  do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
          </td>
        <% end %>
        
        <% if current_user.admin? %>
        <td>
          <%= link_to booking, method: :delete, data: { confirm: 'Are you sure?' }  do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
        </td>
        <% end %>

    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<!--<h1>New Booking</h1>-->
<script language="Javascript">
  Stripe.setPublishableKey("<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>");
</script>

<%= render 'form' %>

<%#= link_to 'Back', bookings_path %>
<%#= link_to 'Pay', new_charge_path %>

app/views/bookings/show.html.erb
<div >
<%= render 'content' %>

<!--Booking Record Info-->
  

  <% if current_user.customer? %>
  <% if @booking.Open? or @booking.Matched? or @booking.Confirmed? %>
      <span><%= link_to t('cancel'), cancel_booking_path(@booking), method: :put, class: "btn btn-success"  %>  </span>
      <span><%= link_to t('edit'), edit_booking_path(@booking), class: "btn btn-success"  %>  </span> 
    <% end %>
  <% elsif current_user.partner? %>
      <% if @booking.Open? %>
  <span><%= link_to t('engage'), engage_booking_path(@booking), method: :put, class: "btn btn-success"  %> </span>
      <% elsif @booking.Matched? %>
  <span><%= link_to t('disengage'), disengage_booking_path(@booking), method: :put, class: "btn btn-success"  %>  </span> 
      <% end %>
  <% elsif current_user.admin? %>
    <% if @booking.Open? or @booking.Matched?%>
      <span><%= link_to t('cancel'), cancel_booking_path(@booking), method: :put, class: "btn btn-success"  %>  </span>
      <span><%= link_to t('reject'), reject_booking_path(@booking), method: :put, class: "btn btn-success"  %>  </span>
  <span><%= link_to t('expire'), expire_booking_path(@booking), method: :put, class: "btn btn-success"  %>  </span>
    <% end %>
  <% end %>
  